<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFramework>net7.0</TargetFramework>
	<AllowUnsafeBlocks>True</AllowUnsafeBlocks>
	<Nullable>disable</Nullable>
  </PropertyGroup>

	<PropertyGroup>
		<Company>Eurobank.Equities</Company>
		<Product>PatioFIX ATHEX Client</Product>
		<AssemblyTitle>PatioFIX.Common</AssemblyTitle>
		<Copyright>Copyright © 2012-2022 Eurobank Equities Α.Ε.Π.Ε.Υ</Copyright>
		<InformationalVersion>1.0</InformationalVersion>
	  <AssemblyVersion>2023.09.04.3</AssemblyVersion>
	  <FileVersion>2023.09.04.3</FileVersion>
	</PropertyGroup>


  <ItemGroup>
	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
	  <_Parameter1>PatioFIX.Admin</_Parameter1>
	</AssemblyAttribute>
	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
	  <_Parameter1>PatioFix.Broker</_Parameter1>
	</AssemblyAttribute>
	  <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
		  <_Parameter1>RawFIXServer</_Parameter1>
	  </AssemblyAttribute>
	  <AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
		  <_Parameter1>ConsoleApp1</_Parameter1>
	  </AssemblyAttribute>
	<AssemblyAttribute Include="System.Runtime.CompilerServices.InternalsVisibleToAttribute">
	  <_Parameter1>GrafanaTest</_Parameter1>
	</AssemblyAttribute>
  </ItemGroup>


  <ItemGroup>
    <None Include="..\.editorconfig" Link=".editorconfig" />
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration" Version="6.0.1" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.FileExtensions" Version="6.0.0" />
    <PackageReference Include="Microsoft.Extensions.Configuration.Json" Version="6.0.0" />
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.3" />
    <PackageReference Include="System.Diagnostics.PerformanceCounter" Version="6.0.1" />
  </ItemGroup>

</Project>
