<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup Label="Globals">
    <SccProjectName>SAK</SccProjectName>
    <SccProvider>SAK</SccProvider>
    <SccAuxPath>SAK</SccAuxPath>
    <SccLocalPath>SAK</SccLocalPath>
  </PropertyGroup>

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net7.0-windows</TargetFramework>
	<Nullable>disable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
  </PropertyGroup>


	<PropertyGroup>
		<Company>Eurobank.Equities</Company>
		<Product>PatioFIX ATHEX Client</Product>
		<AssemblyTitle>PatioFIX.Admin</AssemblyTitle>
		<Copyright>Copyright © 2012-2022 Eurobank Equities Α.Ε.Π.Ε.Υ</Copyright>
		<InformationalVersion>1.0</InformationalVersion>
	  <AssemblyVersion>2023.10.06.1</AssemblyVersion>
	  <FileVersion>2023.10.06.1</FileVersion>
	</PropertyGroup>
	
  <ItemGroup>
    <PackageReference Include="NLog" Version="4.7.15" />
    <PackageReference Include="System.ServiceProcess.ServiceController" Version="6.0.0" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Resources\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PatioFIX.Common\PatioFIX.Common.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="appsettings.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\FIX_MESSAGES_IN_00.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
    <None Update="TestFiles\FIX_MESSAGES_IN_02.txt">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

</Project>